In [2]:
import numpy as np

numpy array

In [3]:
benimListem = [30,40,50]

In [4]:
type(benimListem)

list

In [5]:
np.array(benimListem)

array([30, 40, 50])

In [6]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [8]:
type(matrixListesi)

list

In [9]:
matrixListesi[1]

[20, 30, 40]

In [11]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

arange

In [12]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

zeros

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

linspace

In [23]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

eye

In [25]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

random

In [29]:
np.random.randn(8)

array([ 0.3750136 , -0.31972287,  0.18257847,  0.92827792, -1.58122637,
        0.52021847, -0.7136956 ,  0.05346939])

In [30]:
np.random.randn(8,8)

array([[ 0.93554156, -0.59280092,  0.46936005,  0.18743323, -0.06135903,
        -0.19273665,  0.47156038, -0.65394346],
       [ 0.2755579 , -1.08982439,  2.5718106 ,  2.33252255,  1.04139909,
         0.23108716, -0.46852825,  0.89749346],
       [-0.66017835, -0.11754301,  0.80511826,  0.11473501, -0.06170242,
         1.27593272,  0.88433042,  0.51920432],
       [-0.52435684, -0.62155364, -0.97840321, -0.48698084, -0.76324066,
         0.89611524, -0.84426971,  1.16610391],
       [-0.17917646,  0.72207215,  1.28972794,  0.61215554,  0.49635714,
         0.53233805,  0.52818988,  0.5225892 ],
       [ 2.23492745,  0.20792781,  1.93530447, -1.07413853, -0.20228389,
         0.82659306, -0.28902137, -0.28052131],
       [-1.06034236,  0.23441324, -0.806491  , -0.32364055, -0.29875226,
        -0.98429317,  1.26273399, -1.11554892],
       [-0.26479988, -1.18949328, -0.51048983,  0.92926419, -1.07967288,
        -1.45810814, -1.15982373,  1.36291183]])

In [33]:
np.random.randint(1,10)

2

In [34]:
np.random.randint(1,10,5)

array([9, 3, 5, 2, 7])

In [35]:
benimNumpyDizim = np.arange(30)

In [36]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
benimRandomDizim = np.random.randint(1,100,20)

In [41]:
benimRandomDizim

array([65, 38, 69, 40,  3, 92, 12, 54, 21, 71, 45, 95, 94, 31, 78, 53, 43,
       96, 26, 19])

numpy dizi methodları

In [42]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [44]:
benimNumpyDizim.max()

29

In [45]:
benimRandomDizim.max()

96

In [46]:
benimNumpyDizim.min()

0

In [47]:
benimRandomDizim.argmax()

17

In [49]:
benimRandomDizim.argmin()

4

In [50]:
benimNumpyDizim.shape

(30,)

In [51]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [52]:
reshapeDizim.shape

(5, 6)

In [53]:
benimDizim = np.arange(0,15)

In [54]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
benimDizim[5]

5

In [57]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [58]:
benimDizim[3:8] = -5

In [59]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [60]:
baskaDizi = np.arange(0,24)

In [61]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [66]:
slicingDizisi = baskaDizi[4:9]

In [67]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [68]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [69]:
slicingDizisi[:] = 700

In [70]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [71]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [74]:
ornekDizi = np.arange(0,24)

In [75]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [76]:
ornekDiziKopyası = ornekDizi.copy()

In [77]:
ornekDiziKopyası

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [78]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [79]:
ornekDiziKopyasıSlicing = ornekDiziKopyası[3:6]

In [80]:
ornekDiziKopyasıSlicing[:] = 800

In [81]:
ornekDiziKopyasıSlicing

array([800, 800, 800])

In [82]:
ornekDiziKopyası

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [83]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

matrix

In [88]:
benimListem2 = [[10,20,30],[20,30,40],[40,50,60]]

In [89]:
benimMatrixDizim = np.array(benimListem2)

In [90]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [91]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [93]:
benimMatrixDizim[1][2]

40

In [94]:
benimMatrixDizim[1,2]

40

In [95]:
benimMatrixDizim[1:,2]

array([40, 60])

In [96]:
yeniListem = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [98]:
yeniMatrix = np.array(yeniListem)

In [99]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [100]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

operasyonlar

In [104]:
yeniBirDizi = np.random.randint(1,100,20)

In [105]:
yeniBirDizi

array([22, 36, 40, 11, 62, 49, 82, 79, 26, 91, 14, 68, 92, 58, 32,  8, 51,
       18, 70, 24])

In [107]:
sonucDizisi = yeniBirDizi > 24

In [110]:
sonucDizisi

array([False,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True, False,
        True, False])

In [111]:
yeniBirDizi[yeniBirDizi > 24]

array([36, 40, 62, 49, 82, 79, 26, 91, 68, 92, 58, 32, 51, 70])

In [112]:
sonDizi = np.arange(0,24)

In [113]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [114]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [115]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [116]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [117]:
sonDizi / sonDizi

C:\Users\bct\AppData\Local\Temp\ipykernel_11612\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [118]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [119]:
np.max(sonDizi)

23

In [120]:
np.min(sonDizi)

0